In [ ]:
from sklearn.linear_model import Perceptron
x=[[0,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]
model = Perceptron()
model.fit(x,y)
model.score(x,y)

1.0

In [ ]:
x1 = [[-0.5,-0.5],[10,-2],[-1,0.8],[3,5],[1,0.2],[-0.1,0.9]]
y1 = model.predict(x1)
print(y1)
model.score(x1,y1)

[0 1 0 1 1 1]


1.0

In [ ]:
x1 = [[0.5,0],[0,0.5]]
y1 = model.predict(x1)
print(y1)
model.score(x1,y1)

[0 0]


1.0

In [ ]:

from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [ ]:
iris=datasets.load_iris()
x = iris.data
y = iris.target
print(x[:5])
print(y[:5])
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
sc=StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
X_test_std = sc.transform(x_test)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:

import pandas as pd
import numpy as np

dataframe = pd.read_csv('/content/crabs.csv')
dataframe.head()
crab_B = dataframe
crab_B.sex = crab_B.sex.apply(lambda x: x.replace("M","1"))
crab_B.sex = crab_B.sex.apply(lambda x: x.replace("F","0"))
print(crab_B)

    speies sex  index  fontallip  rearwidth  length  width  depth
0        B   1      1        8.1        6.7    16.1   19.0    7.0
1        B   1      2        8.8        7.7    18.1   20.8    7.4
2        B   1      3        9.2        7.8    19.0   22.4    7.7
3        B   1      4        9.6        7.9    20.1   23.1    8.2
4        B   1      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      O   0     46       21.4       18.0    41.2   46.2   18.7
196      O   0     47       21.7       17.1    41.7   47.2   19.6
197      O   0     48       21.9       17.2    42.6   47.4   19.5
198      O   0     49       22.5       17.2    43.0   48.7   19.8
199      O   0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [ ]:

x = crab_B.drop(['speies','sex','index'],axis = 1)
print(x)
y = crab_B.sex
print(y)
     

     fontallip  rearwidth  length  width  depth
0          8.1        6.7    16.1   19.0    7.0
1          8.8        7.7    18.1   20.8    7.4
2          9.2        7.8    19.0   22.4    7.7
3          9.6        7.9    20.1   23.1    8.2
4          9.8        8.0    20.3   23.0    8.2
..         ...        ...     ...    ...    ...
195       21.4       18.0    41.2   46.2   18.7
196       21.7       17.1    41.7   47.2   19.6
197       21.9       17.2    42.6   47.4   19.5
198       22.5       17.2    43.0   48.7   19.8
199       23.1       20.2    46.2   52.5   21.1

[200 rows x 5 columns]
0      1
1      1
2      1
3      1
4      1
      ..
195    0
196    0
197    0
198    0
199    0
Name: sex, Length: 200, dtype: object


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
model = Perceptron(max_iter = 100, eta0 = 0.1, random_state = 0)
#model: số lần học
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print("Độ chính xác của mô hình: ", accuracy_score(y_test, y_pred))

['0' '0' '0' '0' '1' '0' '1' '0' '1' '1' '1' '0' '0' '0' '1' '0' '1' '0'
 '1' '1' '1' '1' '1' '1' '0' '0' '1' '0' '0' '1' '1' '1' '1' '1' '0' '0'
 '1' '1' '1' '0' '0' '1' '1' '0' '1' '1' '1' '1' '0' '0' '0' '0' '1' '1'
 '0' '1' '0' '0' '1' '1']
187    0
64     0
150    0
192    0
148    1
196    0
146    1
93     0
37     1
8      1
0      1
98     0
55     0
73     0
152    0
167    0
5      1
174    0
26     1
48     1
116    1
11     1
135    1
47     1
89     0
88     0
140    1
188    0
195    0
110    1
126    1
50     0
119    1
103    1
194    0
170    0
101    1
138    1
25     1
153    0
90     0
17     1
13     1
169    0
127    1
147    1
124    1
44     1
199    0
154    0
56     0
157    0
117    1
108    1
86     0
137    1
160    0
87     0
133    1
38     1
Name: sex, dtype: object
Độ chính xác của mô hình:  0.9666666666666667


In [ ]:
data = pd.read_csv('/content/crabs.csv')
data.head()
crab=data
crab.speies = crab.speies.apply(lambda x: x.replace("B","1"))
crab.speies = crab.speies.apply(lambda x: x.replace("O","0"))
print(crab)
x = crab.drop(['speies','sex','index'],axis = 1)
print(x)
y = crab.speies
print(y)
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
model = Perceptron(max_iter = 100, eta0 = 0.1, random_state = 0)
#model: số lần học
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print("Độ chính xác của mô hình: ", accuracy_score(y_test, y_pred))

    speies sex  index  fontallip  rearwidth  length  width  depth
0        1   M      1        8.1        6.7    16.1   19.0    7.0
1        1   M      2        8.8        7.7    18.1   20.8    7.4
2        1   M      3        9.2        7.8    19.0   22.4    7.7
3        1   M      4        9.6        7.9    20.1   23.1    8.2
4        1   M      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      0   F     46       21.4       18.0    41.2   46.2   18.7
196      0   F     47       21.7       17.1    41.7   47.2   19.6
197      0   F     48       21.9       17.2    42.6   47.4   19.5
198      0   F     49       22.5       17.2    43.0   48.7   19.8
199      0   F     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]
     fontallip  rearwidth  length  width  depth
0          8.1        6.7    16.1   19.0    7.0
1          8.8        7.7    18.1   20.8    7.4
2          9.2        7.8    19.0   22.4